// <auto-generated />
using System;
using DocumentRetentionAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DocumentRetentionAPI.Migrations
{
    [DbContext(typeof(DRDBContext))]
    [Migration("20210914163325_CreateDB")]
    partial class CreateDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DocumentRetentionAPI.Models.Clients", b =>
                {
                    b.Property<int>("IDClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreationUser")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IDClient");

                    b.HasIndex("CreationUser");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("DocumentRetentionAPI.Models.DocType", b =>
                {
                    b.Property<int>("IDDT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreationUser")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IDDT");

                    b.HasIndex("CreationUser");

                    b.ToTable("DocType");
                });

            modelBuilder.Entity("DocumentRetentionAPI.Models.Documents", b =>
                {
                    b.Property<int>("IDDocument")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreationUser")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDDT")
                        .HasColumnType("int");

                    b.Property<int>("IDProcesses")
                        .HasColumnType("int");

                    b.Property<int>("IDProjects")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IDDocument");

                    b.HasIndex("CreationUser");

                    b.HasIndex("IDDT");

                    b.HasIndex("IDProcesses");

                    b.HasIndex("IDProjects");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("DocumentRetentionAPI.Models.Processes", b =>
                {
                    b.Property<int>("IDProcesses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreationUser")
                        .HasColumnType("bigint");

                    b.Property<long>("IDOwner")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("NameOwner")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("UpdaeAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IDProcesses");

                    b.HasIndex("CreationUser");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("DocumentRetentionAPI.Models.Projects", b =>
                {
                    b.Property<int>("IDProjects")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreationUser")
                        .HasColumnType("bigint");

                    b.Property<int>("IDClient")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IDProjects");

                    b.HasIndex("CreationUser");

                    b.HasIndex("IDClient");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("DocumentRetentionAPI.Models.Roles", b =>
                {
                    b.Property<int>("IDRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IDRole");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("DocumentRetentionAPI.Models.Users", b =>
                {
                    b.Property<long>("IDUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("IDRole")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("UID")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IDUser");

                    b.HasIndex("IDRole");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DocumentRetentionAPI.Models.Clients", b =>
                {
                    b.HasOne("DocumentRetentionAPI.Models.Users", "user")
                        .WithMany("clietn")
                        .HasForeignKey("CreationUser")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("DocumentRetentionAPI.Models.DocType", b =>
                {
                    b.HasOne("DocumentRetentionAPI.Models.Users", "user")
                        .WithMany("docType")
                        .HasForeignKey("CreationUser")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("DocumentRetentionAPI.Models.Documents", b =>
                {
                    b.HasOne("DocumentRetentionAPI.Models.Users", "user")
                        .WithMany("document")
                        .HasForeignKey("CreationUser")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DocumentRetentionAPI.Models.DocType", "docType")
                        .WithMany("document")
                        .HasForeignKey("IDDT")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DocumentRetentionAPI.Models.Processes", "process")
                        .WithMany("document")
                        .HasForeignKey("IDProcesses")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DocumentRetentionAPI.Models.Projects", "project")
                        .WithMany("document")
                        .HasForeignKey("IDProjects")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("docType");

                    b.Navigation("process");

                    b.Navigation("project");

                    b.Navigation("user");
                });

            modelBuilder.Entity("DocumentRetentionAPI.Models.Processes", b =>
                {
                    b.HasOne("DocumentRetentionAPI.Models.Users", "user")
                        .WithMany("process")
                        .HasForeignKey("CreationUser")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("DocumentRetentionAPI.Models.Projects", b =>
                {
                    b.HasOne("DocumentRetentionAPI.Models.Users", "user")
                        .WithMany("project")
                        .HasForeignKey("CreationUser")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DocumentRetentionAPI.Models.Clients", "client")
                        .WithMany("project")
                        .HasForeignKey("IDClient")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("client");

                    b.Navigation("user");
                });

            modelBuilder.Entity("DocumentRetentionAPI.Models.Users", b =>
                {
                    b.HasOne("DocumentRetentionAPI.Models.Roles", "role")
                        .WithMany("user")
                        .HasForeignKey("IDRole")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("DocumentRetentionAPI.Models.Clients", b =>
                {
                    b.Navigation("project");
                });

            modelBuilder.Entity("DocumentRetentionAPI.Models.DocType", b =>
                {
                    b.Navigation("document");
                });

            modelBuilder.Entity("DocumentRetentionAPI.Models.Processes", b =>
                {
                    b.Navigation("document");
                });

            modelBuilder.Entity("DocumentRetentionAPI.Models.Projects", b =>
                {
                    b.Navigation("document");
                });

            modelBuilder.Entity("DocumentRetentionAPI.Models.Roles", b =>
                {
                    b.Navigation("user");
                });

            modelBuilder.Entity("DocumentRetentionAPI.Models.Users", b =>
                {
                    b.Navigation("clietn");

                    b.Navigation("docType");

                    b.Navigation("document");

                    b.Navigation("process");

                    b.Navigation("project");
                });
#pragma warning restore 612, 618
        }
    }
}
